org: susorg
service: alerta-utec-backend

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::516314868592:role/LabRole

  environment:

    DB_NAME: { Ref: DBUsuarios }
    EVENT_BUS_NAME: ${self:custom.miBusDeEventos}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    INCIDENTS_TABLE: { Ref: IncidenciasTable }
    DB_CONEXIONES: { Ref: DBConexiones }


  role: arn:aws:iam::187904908036:role/LabRole
  httpApi:
    cors: true

custom:
  # 2. Define el nombre aquí para poder reusarlo
  miBusDeEventos: mi-foro-eventos-${self:provider.stage}

build:
  esbuild:
    banner:
      js: |
        import { createRequire } from 'node:module';
        globalThis.require = createRequire(import.meta.url);

functions:
  register:
    handler: src/lambdas/register.handler
    events:
      - httpApi:
          path: /register
          method: post

  login:
    handler: src/lambdas/login.handler
    events:
      - httpApi:
          path: /login
          method: post

  authenticate:
    handler: src/lambdas/authenticate.handler
    events:
      - websocket:
          route: authenticate

  connect:
    handler: src/lambdas/ws/Connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/lambdas/ws/Disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: src/lambdas/ws/default.handler
    events:
      - websocket:
          route: $default

  listarIncidencias:
    handler: src/lambdas/ws/ListarIncidencias.handler
    events:
      - websocket:
          route: listarIncidencias

  priorizarHorizontalmente:
    handler: src/lambdas/ws/PriorizarHorizontalmente.handler
    events:
      - websocket:
          route: priorizarHorizontalmente

  priorizarVerticalmente:
    handler: src/lambdas/ws/PriorizarVerticalmente.handler
    events:
      - websocket:
          route: priorizarVerticalmente

  cerrarIncidente:
    handler: src/lambdas/ws/CerrarIncidente.handler
    events:
      - websocket:
          route: cerrarIncidente
  
  resolverIncidente:
    handler: src/lambdas/ws/ResolverIncidente.handler
    events:
      - websocket:
          route: resolverIncidente

  filtrarIncidencias:
    handler: src/lambdas/ws/FiltrarIncidente.handler
    events:
      - websocket:
          route: filtrarIncidencias



resources:
  Resources:

    # ------------------------
    # Tabla DynamoDB Usuarios
    # ------------------------
    DBUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: correo     # <-- Añadido
            AttributeType: S
          - AttributeName: codigo     # <-- Añadido
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: correo-index
            KeySchema:
              - AttributeName: correo
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: codigo-index
            KeySchema:
              - AttributeName: codigo
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    MiForoEventBus:
      Type: AWS::Events::EventBus
      Properties:
        # 5. Este es el nombre físico
        Name: ${self:custom.miBusDeEventos}
    # ------------------------
    # Tabla DynamoDB Incidencias
    # ------------------------
    IncidenciasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: incidenciaId
            AttributeType: S
        KeySchema:
          - AttributeName: incidenciaId
            KeyType: HASH

    # ------------------------
    # Tabla DynamoDB Conexiones
    # ------------------------
    DBConexiones:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          # Clave principal de la tabla (PK)
          - AttributeName: connectionId
            AttributeType: S
          # Clave de ordenación (SK) y clave del GSI (GSI-PK)
          - AttributeName: viewId
            AttributeType: S
            
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: viewId
            KeyType: RANGE # Hacemos que la clave de ordenación sea 'viewId'
            
        # El GSI "inverso" para buscar por vista
        GlobalSecondaryIndexes:
          - IndexName: view-index # Índice para buscar por vista
            KeySchema:
              - AttributeName: viewId
                KeyType: HASH
              - AttributeName: connectionId
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY # Solo necesitamos los IDs
