org: tuorg
service: alerta-utec-backend

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::{iam}:role/LabRole

  environment:
    DB_NAME: { Ref: DBUsuarios }
    EVENT_BUS_NAME: ${self:custom.miBusDeEventos}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}
    INCIDENTS_TABLE: { Ref: IncidenciasTable }

  role: arn:aws:iam::187904908036:role/LabRole
  httpApi:
    cors: true

custom:
  # 2. Define el nombre aquí para poder reusarlo
  miBusDeEventos: mi-foro-eventos-${self:provider.stage}

build:
  esbuild:
    banner:
      js: |
        import { createRequire } from 'node:module';
        globalThis.require = createRequire(import.meta.url);

functions:
  register:
    handler: src/lambdas/register.handler
    events:
      - httpApi:
          path: /register
          method: post

  login:
    handler: src/lambdas/login.handler
    events:
      - httpApi:
          path: /login
          method: post

  connect:
    handler: dist/lambdas/ws/connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: dist/lambdas/ws/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: dist/lambdas/ws/default.handler
    events:
      - websocket:
          route: $default

  listarIncidencias:
    handler: dist/lambdas/ws/ListarIncidencias.handler
    events:
      - websocket:
          route: listarIncidencias

  priorizarHorizontalmente:
    handler: dist/lambdas/ws/PriorizarHorizontalmente.handler
    events:
      - websocket:
          route: priorizarHorizontalmente

  priorizarVerticalmente:
    handler: dist/lambdas/ws/PriorizarVerticalmente.handler
    events:
      - websocket:
          route: priorizarVerticalmente

  cerrarIncidente:
    handler: dist/lambdas/ws/CerrarIncidente.handler
    events:
      - websocket:
          route: cerrarIncidente



resources:
  Resources:

    # ------------------------
    # Tabla DynamoDB Usuarios
    # ------------------------
    DBUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: correo     # <-- Añadido
            AttributeType: S
          - AttributeName: codigo     # <-- Añadido
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: correo-index
            KeySchema:
              - AttributeName: correo
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: codigo-index
            KeySchema:
              - AttributeName: codigo
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    MiForoEventBus:
      Type: AWS::Events::EventBus
      Properties:
        # 5. Este es el nombre físico
        Name: ${self:custom.miBusDeEventos}
    # ------------------------
    # Tabla DynamoDB Incidencias
    # ------------------------
    IncidenciasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: IncidenciasTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: incidenciaId
            AttributeType: S
        KeySchema:
          - AttributeName: incidenciaId
            KeyType: HASH
