service: alerta-utec-backend

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    DB_NAME: { Ref: DBUsuarios }
    EVENT_BUS_NAME: ${self:custom.miBusDeEventos}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN}

  role: arn:aws:iam::187904908036:role/LabRole
  httpApi:
    cors: true

custom:
  # 2. Define el nombre aqu√≠ para poder reusarlo
  miBusDeEventos: mi-foro-eventos-${self:provider.stage}

build:
  esbuild:
    banner:
      js: |
        import { createRequire } from 'node:module';
        globalThis.require = createRequire(import.meta.url);

functions:
  register:
    handler: src/lambdas/register.handler
    events:
      - httpApi:
          path: /register
          method: post

  login:
    handler: src/lambdas/login.handler
    events:
      - httpApi:
          path: /login
          method: post

resources:
  Resources:
    DBUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: correo     # <-- A√±adido
            AttributeType: S
          - AttributeName: codigo     # <-- A√±adido
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        
        # üëá ESTA ES LA PARTE IMPORTANTE üëá
        GlobalSecondaryIndexes:
          - IndexName: correo-index
            KeySchema:
              - AttributeName: correo
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: codigo-index
            KeySchema:
              - AttributeName: codigo
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    MiForoEventBus:
      Type: AWS::Events::EventBus
      Properties:
        # 5. Este es el nombre f√≠sico
        Name: ${self:custom.miBusDeEventos}
